<?php

/**
 * @file
 * artigos_relacionados.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 */
function artigos_relacionados_theme($existing, $type, $theme, $path) {
  return [
    'artigos_relacionados_carousel' => [
      'variables' => [
        'articles' => [],
      ],
      'template' => 'artigos-relacionados-carousel',
    ],
  ];
}

/**
 * Implements hook_help().
 */
function artigos_relacionados_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.artigos_relacionados':
      return '<p>' . t('Mostra artigos relacionados baseados nas tags do artigo atual.') . '</p>';
  }
}
